config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'events#index'
 
  resources :users, only: [:new, :create, :show, :index]
  resources :events

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'
  get 'authorized', to: 'sessions#page_requires_login'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :event_creator, class_name: 'User'
  has_many :invitations, foreign_key: :attended_event_id
  has_many :event_attendees, through: :invitations, source: :event_attendee

  scope :past, -> { where(['event_date < ?', Date.today]) }
  scope :upcoming, -> { where(['event_date > ?', Date.today]) }

  validates :event_name, :event_description, :event_location, :event_date, presence: true
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :created_events, foreign_key: :event_creator_id, class_name: 'Event'
  has_many :invitations, foreign_key: :event_attendee_id
  has_many :attended_events, through: :invitations

  validates :name, :email, presence: true
  validates_uniqueness_of :name

  scope :past, -> { where(['event_date < ?', Date.today]) }
  scope :upcoming, -> { where(['event_date > ?', Date.today]) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :logged_in?
  before_action :authorized

  def current_user
    User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    return if logged_in?

    flash[:danger] = 'You need to be logged in to perform that action'
    redirect_to root_path
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_user, except: %i[index show]

  def index
    @past = Event.past
    @upcoming = Event.upcoming
  end

  def new
    @event = current_user.created_events.build
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      flash[:notice] = 'The event was created succesfully'
      redirect_to users_path
    else
      flash[:alert] = 'Something went grong, try again'
      render 'new'
    end
  end

  def current_user
    session[:user_id] && User.find(session[:user_id])
  end

  def show
    @event = Event.find(params[:id])
    @event.event_attendees.each(&:name)
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :event_location, :event_date, :event_description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: %i[new create welcome]

  def new; end

  def create
    @user = User.find_by(name: params[:name])

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      flash.now[:danger] = 'There was something wrong with the login information'
      redirect_to '/login'
    end
  end

  def login; end

  def welcome; end

  def page_requires_login; end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'You have successfully logged out'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: %i[new create]

  def new
    @user = User.new
    redirect_to user_path(current_user) if logged_in?
  end

  def create
    @user = User.create(params.require(:user).permit(:name, :email,
                                                     :password))
    session[:user_id] = @user.id
    redirect_to '/welcome'
  end

  def show
    @user = User.find_by_id(params[:id])
    @upcoming_events = @user.attended_events.upcoming
    @prev_events = @user.attended_events.past
    flash[:error] = 'User not found' unless @user
  end

  def index
    @users = User.all
    @events = Event.all
  end

  private

  def require_login
    # do stuff to check if user is logged in
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_event_creator
    User.find(@event.event_creator_id).name
  end

  def current_user
    session[:user_id] && User.find(session[:user_id])
  end

  def navbar_log_buttons
    links = ''
    if logged_in?
      links << link_to('My Profile', user_path(session[:user_id]))
      links << '  ' + link_to('Sign out', logout_path, method: :delete)
    else
      links << link_to('Log in', login_path, method: :get)
      links << '  ' + link_to('Sign up', new_user_path)
    end
    links.html_safe
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/events/index.html.erb
<h1>This is the index</h1><br/>


 <p> Upcoming Events</p>

<% @upcoming.each do |event| %>


<%= link_to event.event_name, event%><br/>
<%= event.event_date%><br/>


<% end %><br/>

<p> Past Events</p>
<% @past.each do |event| %>


<%= link_to event.event_name, event%><br/>
<%= event.event_date%><br/>


<% end %><br/>



<%= link_to 'New Event', new_event_path %><br/>

<%= link_to 'Back to Users', users_path %>

app/views/events/new.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

<h1>New event's form</h1><br/>

<%= form_for(@event) do |f| %> <br/>

<%= f.text_field :event_name, autofocus: true, placeholder: 'Event name' %><br/>

<%= f.datetime_select :event_date %><br/>

<%= f.text_field :event_location, placeholder: 'Event Location' %><br/>

<%= f.text_area :event_description, placeholder: 'Event Description' %><br/>

<%= f.submit %><br/>

<% end %><br/>

<%= link_to 'Back to users', users_path %>

app/views/events/show.html.erb
<h1><%= @event.event_name %> </h1>


<p><strong>Description:</strong> <%= @event.event_description %></p>
<p><strong>Location:</strong> <%= @event.event_location %></p>
<p><strong>Date:</strong> <%= @event.event_date %></p>

<span> This event was created by <%= current_event_creator %> </span>








 <p>This is the list of Attendees to the event </p>

<ul>
<% @event.event_attendees.each do |attend| %>

<li><%= attend.name %>


<% end %>

</ul>

<%= link_to 'Back', users_path %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path, class: "" %>

<%= link_to 'Events', events_path %>

<%= link_to 'Create Event', new_event_path, class: "" %>

<%= link_to 'Users', users_path %>


 <%= navbar_log_buttons %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>


    <% flash.each do |name, msg| %>
      <div class='alert alert-<%="#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">
          &#215;
        </a>
        <%= msg %>
      </div>
    <% end %>

  <div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>This is the index</h1><br/>

<% @users.each do |user| %>
<%= link_to user.name, user%><br/>
  
<% end %><br/>

<%= link_to 'Events', events_path %>

app/views/users/new.html.erb
<h1>New User form</h1>

<%= form_for @user do |f|%>
  <%= f.label :name%><br>
  <%= f.text_field :name%><br>
  <%= f.label :email%><br>
  <%= f.text_field :email%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password%><br>
  <%= f.submit %>
<%end%>

app/views/users/show.html.erb
<h1>Show page</h1>

<h2>Hello <%= @user.name %>! </h2>

<p> This is the list of events you have created </p>

<ul>
<% @user.created_events.each do |event| %>

<li><%= link_to event.event_name, event %>
<p> <%= event.event_description %> </p>
<p> <%= event.event_location %> </p>
<p> <%= event.event_date %> </p>

<% end %>


<b> Upcoming Events, this is the list of events you will attend</b><br/>

<% @upcoming_events.each do |event| %>


<%= link_to event.event_name, event%><br/>
<%= event.event_date%><br/>


<% end %><br/>

<b> Past Events, this is the list of events you have attended</b><br/>
<%  @prev_events.each do |event| %>


<%= link_to event.event_name, event%><br/>
<%= event.event_date%><br/>


<% end %><br/>



 
<%= link_to 'Back', users_path %>